# SPDX-License-Identifier: GPL-2.0-only
################################################################################
#
# Linux driver for VMware's vmxnet3 ethernet NIC.
#
# Copyright (C) 2007-2016, VMware, Inc. All Rights Reserved.
#
# Maintained by: pv-drivers@vmware.com
#
#
################################################################################

#
# Makefile for the VMware vmxnet3 ethernet NIC driver
#

obj-$(CONFIG_VMXNET3) += vmxnet3.o

vmxnet3-objs := vmxnet3_drv.o vmxnet3_ethtool.o
